version: 2
updates:
- package-ecosystem: npm
  directory: "/4-vue-cli"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: npm
  directory: "/4-vue-cli-test"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: npm
  directory: "/5-parcel"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: npm
  directory: "/5-parcel-test"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: npm
  directory: "/6-nette"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
